apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
      - name: abc
        image: ${IMAGE_NAME}:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
