- hosts: all
  become: yes
  tasks:
    - name: Disable swap
      shell: |
        swapoff -a
        sed -i.bak '/ swap / s/^/#/' /etc/fstab

- hosts: master
  become: yes
  tasks:
    - name: Install Docker
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installDocker.sh -P /tmp
        chmod 755 /tmp/installDocker.sh
        bash /tmp/installDocker.sh
        systemctl restart docker.service

    - name: Install CRI-Docker
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installCRIDockerd.sh -P /tmp
        chmod 755 /tmp/installCRIDockerd.sh
        bash /tmp/installCRIDockerd.sh
        systemctl restart cri-docker.service

    - name: Install kubeadm, kubelet, kubectl
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installK8S.sh -P /tmp
        chmod 755 /tmp/installK8S.sh
        bash /tmp/installK8S.sh

    - name: Validate installations
      shell: |
        docker -v
        cri-dockerd --version
        kubeadm version -o short
        kubelet --version
        kubectl version --client

    - name: Initialize Kubernetes Master Node
      shell: |
        kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock --ignore-preflight-errors=all
      register: kubeadm_init

    - name: Configure kubeconfig for ubuntu
      shell: |
        mkdir -p /home/ubuntu/.kube
        cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        chown ubuntu:ubuntu /home/ubuntu/.kube/config

    - name: Install Calico networking
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml

    - name: Generate kubeadm join command
      shell: kubeadm token create --print-join-command
      register: kube_join

    - set_fact:
        kube_join_command: "{{ kube_join.stdout }} --cri-socket unix:///var/run/cri-dockerd.sock"

- hosts: workers
  become: yes
  tasks:
    - name: Install Docker
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installDocker.sh -P /tmp
        chmod 755 /tmp/installDocker.sh
        bash /tmp/installDocker.sh
        systemctl restart docker.service

    - name: Install CRI-Docker
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installCRIDockerd.sh -P /tmp
        chmod 755 /tmp/installCRIDockerd.sh
        bash /tmp/installCRIDockerd.sh
        systemctl restart cri-docker.service

    - name: Install kubeadm, kubelet, kubectl
      shell: |
        wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installK8S.sh -P /tmp
        chmod 755 /tmp/installK8S.sh
        bash /tmp/installK8S.sh

    - name: Enable networking features
      shell: |
        modprobe br_netfilter
        echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
        echo 1 > /proc/sys/net/ipv4/ip_forward

    - name: Validate installations
      shell: |
        docker -v
        cri-dockerd --version
        kubeadm version -o short
        kubelet --version
        kubectl version --client

    - name: Join worker to cluster
      shell: "sudo {{ hostvars[groups['master'][0]]['kube_join_command'] }}"
