---
- name: Install Docker on Ubuntu 22.04
  hosts: all
  become: true
  vars:
    docker_user: ubuntu

  tasks:

    # ---------------- Remove Conflicting Packages ----------------
    - name: Remove conflicting Ubuntu containerd
      apt:
        name: containerd
        state: absent
        purge: yes
        autoremove: yes

    # ---------------- Install Dependencies ----------------
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    # ---------------- Add Docker GPG Key ----------------
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # ---------------- Add Docker Repository ----------------
    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    # ---------------- Update APT Cache ----------------
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    # ---------------- Install Docker Packages ----------------
    - name: Install Docker packages (official)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    # ---------------- Enable and Start Docker ----------------
    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    # ---------------- Add User to Docker Group ----------------
    - name: Add ubuntu user to docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes

    # ---------------- Verify Docker Installation ----------------
    - name: Verify Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Show Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
